config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'links#index'
  resources :links, only: [:index, :new, :create]
  get 'links/:path', to: 'links#redirect', as: 'link_redirect'
  get 'links/:path/info', to: 'links#show', as: 'link'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
# frozen_string_literal: true

class Link < ApplicationRecord # rubocop:disable Style/Documentation
  validates :original_url, presence: true

  after_create :create_short_url

  def create_short_url
    self.short_url = url_encode(id)
    save
  end

  private

  def url_encode(id)
    return alphabet[0] if id.zero?

    s = ''
    base = alphabet.length
    while id.positive?
      s << alphabet[id.modulo(base)]
      id /= base
    end
    s.reverse
  end

  def alphabet
    'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'.split(//)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/links_controller.rb
# frozen_string_literal: true

class LinksController < ApplicationController # rubocop:disable Style/Documentation
  # GET /links
  def index
    links = Link.all
    render :index, locals: { links: links }
  end

  # GET /links/new
  def new
    link = Link.new
    render :new, locals: { link: link }
  end

  # POST /links
  def create
    link = Link.new(original_url: "https://#{link_params[:domain]}")
    if link.save
      redirect_to links_path, notice: 'Link was successfully created.'
    else
      render :new, locals: { link: link }
    end
  end

  # GET /links/:path
  def redirect # rubocop:disable Metrics/AbcSize
    if link
      link.ip_addresses << request.remote_ip unless link.ip_addresses.include?(request.remote_ip)
      link.save
      redirect_to link.original_url
    else
      redirect_back(fallback_location: links_path, notice: "Can't find link with given short_url")
    end
  end

  # GET /links/:path/info
  def show
    if link
      render :show, locals: { link: link }
    else
      redirect_back(fallback_location: links_path, notice: "Can't find link with given short_url")
    end
  end

  private

  def link
    @link ||= Link.find_by(short_url: params[:path])
  end

  def link_params
    params.require(:link).permit(:domain)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tinyurl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with(model: link, local: true) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
        <% link.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    https:// <%= form.text_field :domain %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/links/_link.html.erb
<tr>
  <td>original_url: <%= link.original_url %></td>
  <td>short_url: <%= link_to link.short_url, link_redirect_path(path: link.short_url) %></td>
  <td><%= link_to 'info', link_path(path: link.short_url) %></td>
</tr>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Links</h1>

<table>
  <thead>
  <tr>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
   <%= render partial: 'link', collection: links, as: :link %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: link %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>
<div>
  <span>
    original url:
  </span>
  <span>
    <%= link.original_url %>
  </span>
</div>
<div>
  <span>
    short url:
  </span>
  <span>
    <%= link.short_url %>
  </span>
</div>
<div>
  <span>
    visitors count:
  </span>
  <span>
    <%= link.ip_addresses.count %>
  </span>
</div>
<%= link_to 'Back', links_path %>